../../../bin/make_tracks_config.pl --assembly  b_malayi_PRJNA10729
../../../bin/make_tracks_config.pl --assembly  c_angaria_PRJNA51225
../../../bin/make_tracks_config.pl --assembly  c_becei_PRJEB28243
../../../bin/make_tracks_config.pl --assembly  c_bovis_PRJEB34497
../../../bin/make_tracks_config.pl --assembly  c_brenneri_PRJNA20035
../../../bin/make_tracks_config.pl --assembly  c_briggsae_PRJNA10731
../../../bin/make_tracks_config.pl --assembly  c_elegans_PRJEB28388
../../../bin/make_tracks_config.pl --assembly  c_elegans_PRJNA13758
../../../bin/make_tracks_config.pl --assembly  c_elegans_PRJNA275000
../../../bin/make_tracks_config.pl --assembly  c_inopinata_PRJDB5687
../../../bin/make_tracks_config.pl --assembly  c_japonica_PRJNA12591
../../../bin/make_tracks_config.pl --assembly  c_latens_PRJNA248912
../../../bin/make_tracks_config.pl --assembly  c_nigoni_PRJNA384657
../../../bin/make_tracks_config.pl --assembly  c_panamensis_PRJEB28259
../../../bin/make_tracks_config.pl --assembly  c_parvicauda_PRJEB12595
../../../bin/make_tracks_config.pl --assembly  c_quiockensis_PRJEB11354
../../../bin/make_tracks_config.pl --assembly  c_remanei_PRJNA53967
../../../bin/make_tracks_config.pl --assembly  c_remanei_PRJNA577507
../../../bin/make_tracks_config.pl --assembly  c_sinica_PRJNA194557
../../../bin/make_tracks_config.pl --assembly  c_sulstoni_PRJEB12601
../../../bin/make_tracks_config.pl --assembly  c_tribulationis_PRJEB12608
../../../bin/make_tracks_config.pl --assembly  c_tropicalis_PRJNA53597
../../../bin/make_tracks_config.pl --assembly  c_uteleia_PRJEB12600
../../../bin/make_tracks_config.pl --assembly  c_waitukubuli_PRJEB12602
../../../bin/make_tracks_config.pl --assembly  c_zanzibari_PRJEB12596
../../../bin/make_tracks_config.pl --assembly  o_tipulae_PRJEB15512
../../../bin/make_tracks_config.pl --assembly  o_volvulus_PRJEB513
../../../bin/make_tracks_config.pl --assembly  p_pacificus_PRJNA12644
../../../bin/make_tracks_config.pl --assembly  p_redivivus_PRJNA186477
../../../bin/make_tracks_config.pl --assembly  s_ratti_PRJEB125
../../../bin/make_tracks_config.pl --assembly  t_muris_PRJEB126
