# JBrowse 2

FROM gmod/jbrowse2-buildenv:1.2

ARG RELEASE=287
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

RUN git clone --single-branch --branch jb2-288 https://github.com/WormBase/website-genome-browsers.git

RUN mkdir -p /usr/share/nginx/html/tools/genome
WORKDIR /usr/share/nginx/html/tools/genome/
RUN jbrowse create --branch save_track_data jbrowse2
#RUN jbrowse create jbrowse2
#RUN sleep 10
#RUN ls /usr/share/nginx/html/tools/genome/jbrowse2/

RUN rm /usr/share/nginx/html/index.html && \
    rm /usr/share/nginx/html/50x.html && \
    cp /website-genome-browsers/jbrowse2/c_elegans.bed /usr/share/nginx/html/tools/genome/jbrowse2/ && \
    cp /website-genome-browsers/jbrowse2/c_elegans.c_remanei.anchors /usr/share/nginx/html/tools/genome/jbrowse2/ && \
    cp /website-genome-browsers/jbrowse2/c_remanei.bed /usr/share/nginx/html/tools/genome/jbrowse2/ && \
    cp /website-genome-browsers/jbrowse2/config/variantColor_plugin.js \
            /usr/share/nginx/html/tools/genome/jbrowse2/variantColor_plugin.js && \
    cp /website-genome-browsers/jbrowse2/config/hex_plugin.js \
            /usr/share/nginx/html/tools/genome/jbrowse2/hex_plugin.js && \
    cp /website-genome-browsers/jbrowse2/logo_wormbase_gradient-150px.png \
            /usr/share/nginx/html/tools/genome/jbrowse2/logo_wormbase_gradient-150px.png && \
    cp /website-genome-browsers/jbrowse2/docker-entrypoint.sh /

#WORKDIR /usr/share/nginx/html/tools/genome

RUN mkdir -p /website-genome-browsers/jbrowse2/config/track_configs/WS$RELEASE

WORKDIR /website-genome-browsers/jbrowse2/config/track_configs/WS$RELEASE

RUN cp /website-genome-browsers/jbrowse2/bin/make_tracks.sh .

RUN bash make_tracks.sh -r $RELEASE

#RUN sleep 5

RUN ../../../bin/make_embed_config.pl --release $RELEASE

RUN ../../../bin/make_global_config.pl --release $RELEASE > config.json

RUN cp config.json /usr/share/nginx/html/tools/genome/jbrowse2/config.json

RUN mkdir -p /usr/share/nginx/html/tools/genome/jbrowse2/embed/
RUN cp *embed.json /usr/share/nginx/html/tools/genome/jbrowse2/embed/

WORKDIR /usr/share/nginx/html/tools/genome/jbrowse2

RUN zip -r jbrowse2-release$RELEASE.zip . -x test_data/\*

RUN AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws s3 cp --acl public-read jbrowse2-release$RELEASE.zip s3://agrjbrowse




VOLUME /data
CMD ["/docker-entrypoint.sh"]
